url: ''
baseurl: ''
title: 'Não tem nome ainda'

plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  pages:
    output: true
    permalink: "/:name"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:year/:i_month/:i_day/:title"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

paginate: 5
paginate_path: "/blog/page/:num"
