source 'https://rubygems.org'

ruby '3.3.0'

gem "jekyll", "~> 4.3.3"
gem 'webrick'

group :jekyll_plugins do
  gem "jekyll-feed"
  gem 'jekyll-paginate'
  gem 'jekyll-postcss'
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end
